-- MySQL Script generated by MySQL Workbench
-- Po 26. február 2018, 13:30:00 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tipos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tipos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tipos` DEFAULT CHARACTER SET utf8 ;
USE `tipos` ;

-- -----------------------------------------------------
-- Table `tipos`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(20) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos`.`login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos`.`login_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idu` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `success` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idu_idx` (`idu` ASC),
  CONSTRAINT `idu`
    FOREIGN KEY (`idu`)
    REFERENCES `tipos`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos`.`bets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos`.`bets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idu` INT NOT NULL,
  `draw_id` INT NULL DEFAULT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_1_idx` (`idu` ASC),
  CONSTRAINT `fk_tickets_1`
    FOREIGN KEY (`idu`)
    REFERENCES `tipos`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos`.`bet_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos`.`bet_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bet1` INT NOT NULL,
  `bet2` INT NOT NULL,
  `bet3` INT NOT NULL,
  `bet4` INT NOT NULL,
  `bet5` INT NOT NULL,
  `idb` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bet_details_1_idx` (`idb` ASC),
  CONSTRAINT `fk_bet_details_1`
    FOREIGN KEY (`idb`)
    REFERENCES `tipos`.`bets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos`.`draw_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos`.`draw_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ball1` INT NOT NULL,
  `ball2` INT NOT NULL,
  `ball3` INT NOT NULL,
  `ball4` INT NOT NULL,
  `ball5` INT NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos`.`token` (
  `id` INT NOT NULL,
  `token` VARCHAR(90) NULL DEFAULT 'null',
  `idu` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_token_1_idx` (`idu` ASC),
  CONSTRAINT `fk_token_1`
    FOREIGN KEY (`idu`)
    REFERENCES `tipos`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos`.`unsuccessful_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos`.`unsuccessful_login` (
  `id` INT NOT NULL,
  `idu` INT NOT NULL,
  `countOfEvents` INT NULL DEFAULT 0,
  `lastEvent` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE USER 'tiper1' IDENTIFIED BY 'reabc';

GRANT ALL ON `tipos`.* TO 'tiper1';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
